### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by MadhurJ20** [ACES-RMDSSOE/Website#1]
# Create Linktree-esque Landing Page for ACES.

## Steps:

1. Create a new branch (probably already created by the time you see this)
2. Copy all your code (with your changes ofcourse) from our [Linktree repo](https://github.com/ACES-RMDSSOE/linktree)
3. Push them here, create a PR & add here for review.
4. We'll merge it here

**Comment by MadhurJ20** [comment]
@Saloni1707 Website isn't optimised for mobile.
Gotta update styles.css 
Web devs in the team, pls help.

**Comment by Saloni1707** [comment]
i'll chk once
